name: Create Submission Zip

on:
  push:
    branches: [main, test2]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Compile project
        run: make

      - name: Run full simulation and capture output
        run: make run > output/live_run.txt

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python dependencies and fonts
        run: |
          python -m pip install --upgrade pip
          pip install Pillow
          sudo apt-get update && sudo apt-get install -y ttf-dejavu-core

      - name: Generate screenshot from live run
        run: python scripts/generate_screenshot.py

      - name: Create submission directory
        run: mkdir submission

      - name: Package submission files
        run: |
          cp -r src submission/
          cp README.txt submission/
          cp output/screenshot_*.png submission/

      - name: Create submission zip
        run: |
          cd submission
          zip -r ../lab2_210167E_210176F.zip .
          cd ..

      - name: Upload submission zip
        uses: actions/upload-artifact@v3
        with:
          name: submission
          path: lab2_210167E_210176F.zip
