name: Create Submission Zip

on:
  push:
    branches: [main, test2]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Ensure zip is available (usually preinstalled)
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Compile project
        run: make

      - name: Prepare output directory
        run: mkdir -p output

      - name: Run full simulation and capture output
        run: make run > output/live_run.txt

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Python dependencies and fonts
        run: |
          python -m pip install --upgrade pip
          pip install Pillow
          sudo apt-get update
          sudo apt-get install -y fonts-dejavu-core || \
            sudo apt-get install -y fonts-liberation || \
            sudo apt-get install -y fonts-noto-core

      - name: Generate screenshot from live run
        run: python scripts/generate_screenshot.py

      - name: Create submission directory
        run: mkdir -p submission

      - name: Package submission files
        run: |
          cp -r src submission/
          cp README.txt submission/
          cp Makefile submission/ || true
          cp output/screenshot_*.png submission/ || true
          cp output/live_run.txt submission/logs.txt

      - name: Create submission zip
        run: |
          cd submission
          zip -r ../lab2_210167E_210176F.zip .
          cd ..

      - name: Upload submission zip
        uses: actions/upload-artifact@v4
        with:
          name: submission
          path: lab2_210167E_210176F.zip
          if-no-files-found: error
          retention-days: 14
